name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npx tsc -noEmit

      - name: Lint
        run: npx eslint . --max-warnings=0

      - name: Unit tests (Vitest)
        run: npx vitest run --reporter=dot --silent

      - name: Build
        run: npm run build

      - name: Start preview server
        run: |
          npx vite preview --port 4173 &
          for i in {1..30}; do
            if curl -sSf http://localhost:4173 > /dev/null; then
              echo "Preview server is up"; break;
            fi
            echo "Waiting for preview server..."; sleep 1;
          done

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Playwright smoke tests
        env:
          BASE_URL: http://localhost:4173
        run: npx playwright test -c .

      - name: Audit dependencies
        continue-on-error: true
        run: npm audit --audit-level=moderate
